// Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
// By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

#define MAX_TERM_VALUE 4000000

int even_fibonacci_numbers()
{
    int term_a = 1;
    int term_b = 2;
    int sum = 0;
    int saved_term_a;

    while (term_a <= MAX_TERM_VALUE)
    {
        if (term_a % 2 == 0)
        {
            sum += term_a;
        }
        
        saved_term_a = term_a;
        term_a = term_b;
        term_b = saved_term_a + term_b;
    }
    
    return sum;
}